version: 2

sources:
  - name: "scraper"
    description: "data coming from the scraper lambda function"
    database: "state_of_the_earth"
    schema: "ingestion"
    tables: 
      - name: "news_articles"
        description: "table with news articles, summaries, and generated images"

models:
  - name: news_articles
    description: "This table contains the articles ingested from news sources."
    columns:
      - name: id
        description: "Auto-incrementing primary key."
      - name: publish_date
        description: "Timestamp of when the article was published."
      - name: source
        description: "Source of the news article."
      - name: link
        description: "URL link to the article."
      - name: title
        description: "Title of the article."
      - name: topic1
        description: "First topic or category related to the article."
      - name: topic2
        description: "Second topic or category related to the article."
      - name: content
        description: "Full content of the article."
      - name: summary
        description: "Summary of the article content."
      - name: image
        description: "URL of the image associated with the article."